library(shiny)
library(markdown)

shinyUI(fluidPage(
	titlePanel('Unit converter'),
		sidebarLayout(
			sidebarPanel("Documentation",
						includeMarkdown("About.md"),width=3
				),
			mainPanel(			
				tabsetPanel(
					tabPanel('Length',
						selectInput('lfrom', "Unit of origin:",
							choices=c(
							"chain",
							"centimeter",
							"foot",
							"furlong",
							"hand",
							"inch",
							"kilometer",
							"link",
							"meter",
							"mile",
							"millimeter",
							"span",
							"yard"),
							selected="meter"),
						selectInput('lto', "Destination unit:",
							choices=c(
							"chain",
							"centimeter",
							"foot",
							"furlong",
							"hand",
							"inch",
							"kilometer",
							"link",
							"meter",
							"mile",
							"millimeter",
							"span",
							"yard"),
							selected="meter"),
						numericInput('lval', 'value to convert :', 0, min = 0, max = 1000000, step = 100),
						h3('Unit of input'),
						verbatimTextOutput("lfrom"),
						h3('Value inputed'),
						verbatimTextOutput("lval"),
						h3('Unit of output'),
						verbatimTextOutput("lto"),
						h3('Converted value: '),
						verbatimTextOutput("lresult"),
						h3('Synthesis: '),
						verbatimTextOutput("lphrase")
						),
					tabPanel('Surface',
						selectInput('sfrom', "Unit of origin:",
							choices=c(
							"acre", 
							"are",
							"hectare", 
							"square_centimeter", 
							"square_foot", 
							"square_inch", 
							"square_kilometer", 
							"square_meter", 
							"square_mile"
							),
							selected="square_meter"),
						selectInput('sto', "Destination unit:",
							choices=c(
							"acre", 
							"are",
							"hectare", 
							"square_centimeter", 
							"square_foot", 
							"square_inch", 
							"square_kilometer", 
							"square_meter", 
							"square_mile"
							),
							selected="square_meter"),
						numericInput('sval', 'value to convert :', 0, min = 0, max = 1000000, step = 100),
						h3('Unit of input'),
						verbatimTextOutput("sfrom"),
						h3('Value inputed'),
						verbatimTextOutput("sval"),
						h3('Unit of output'),
						verbatimTextOutput("sto"),
						h3('Converted value: '),
						verbatimTextOutput("sresult"),
						h3('Synthesis: '),
						verbatimTextOutput("sphrase")
						),
					tabPanel('Volume',
						selectInput('vfrom', "Unit of origin:",
							choices=c(
							"centiliter", 
							"cubic_centimeter",
							"cubic_foot", 
							"cubic_meter", 
							"cubic_millimeter",
							"fluid_ounce", 
							"gallon", 
							"liter", 
							"milliliter",
							"pint", 
							"quart"), 
							selected="cubic_meter"),
						selectInput('vto', "Destination unit:",
							choices=c(
							"centiliter", 
							"cubic_centimeter",
							"cubic_foot", 
							"cubic_meter", 
							"cubic_millimeter",
							"fluid_ounce", 
							"gallon", 
							"liter", 
							"milliliter",
							"pint", 
							"quart"), 
							selected="cubic_meter"),
						numericInput('vval', 'value to convert :', 0, min = 0, max = 1000000, step = 100),
						h3('Unit of input'),
						verbatimTextOutput("vfrom"),
						h3('Value inputed'),
						verbatimTextOutput("vval"),
						h3('Unit of output'),
						verbatimTextOutput("vto"),
						h3('Converted value: '),
						verbatimTextOutput("vresult"),
						h3('Synthesis: '),
						verbatimTextOutput("vphrase")
						),
					tabPanel('Weight',
						selectInput('wfrom', "Unit of origin:",
							choices=c(
							"gram", 
							"kilogram",
							"long_ton", 
							"ounce", 
							"pound", 
							"short_ton", 
							"ton" 
							),
							selected="gram"),
						selectInput('wto', "Destination unit:",
							choices=c(
							"gram", 
							"kilogram",
							"long_ton", 
							"ounce", 
							"pound", 
							"short_ton", 
							"ton"
							),
							selected="gram"),
						numericInput('wval', 'value to convert :', 0, min = 0, max = 1000000, step = 100),
						h3('Unit of input'),
						verbatimTextOutput("wfrom"),
						h3('Value inputed'),
						verbatimTextOutput("wval"),
						h3('Unit of output'),
						verbatimTextOutput("wto"),
						h3('Converted value: '),
						verbatimTextOutput("wresult"),
						h3('Synthesis: '),
						verbatimTextOutput("wphrase")
						)
					)
				)
			)
		)
	)